<template>
  <div class="mx-auto max-w-7xl space-y-4 py-8 px-4">
    <div class="text-center">
      <h2 class="font-bold text-2xl">Privacy Policy</h2>
    </div>
    <div class="card p-10 space-y-5">
      <div>
        <h3 class="font-semibold">1. Introduction</h3>
        <p>
          By accessing the website at https://www.pointhub.app, you are agreeing to be bound by these terms of service,
          all applicable laws and regulations, and agree that you are responsible for compliance with any applicable
          local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          The materials contained in this website are protected by applicable copyright and trademark law.
        </p>
      </div>
      <div>
        <h3 class="font-semibold">2. Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <table>
          <tbody>
            <tr>
              <td class="font-bold align-top">Account</td>
              <td class="px-4">
                means a unique account created for You to access our Service or parts of our Service.
              </td>
            </tr>
            <tr>
              <td class="font-bold align-top">Company</td>
              <td class="px-4">
                (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
                this Agreement) refers to PT Bumi Inovasi Ganapatih, Indonesia.
              </td>
            </tr>
            <tr>
              <td class="font-bold align-top">Cookies</td>
              <td class="px-4">
                are small files that are placed on Your computer, mobile device or any other device by a website,
                containing the details of Your browsing history on that website among its many uses.
              </td>
            </tr>
            <tr>
              <td class="font-bold align-top">Device</td>
              <td class="px-4">
                means any device that can access the Service such as a computer, a cellphone or a digital tablet.
              </td>
            </tr>
            <tr>
              <td class="font-bold align-top">Personal Data</td>
              <td class="px-4">is any information that relates to an identified or identifiable individual.</td>
            </tr>
            <tr>
              <td class="font-bold align-top">Service</td>
              <td class="px-4">refers to the Website.</td>
            </tr>
            <tr>
              <td class="font-bold align-top">Third-party Social Media Service</td>
              <td class="px-4">
                refers to any website or any social network website through which a User can log in or create an account
                to use the Service.
              </td>
            </tr>
            <tr>
              <td class="font-bold align-top">Usage data</td>
              <td class="px-4">
                refers to data collected automatically, either generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page visit).
              </td>
            </tr>
            <tr>
              <td class="font-bold align-top">Website</td>
              <td class="px-4">
                refers to Pointhub App, accessible from
                <a href="https://www.pointhub.app" rel="external nofollow noopener" target="_blank"
                  >https://www.pointhub.app</a
                >
              </td>
            </tr>
            <tr>
              <td class="font-bold align-top">You</td>
              <td class="px-4">
                means the individual accessing or using the Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as applicable.
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div>
        <h3 class="font-semibold">3. Collecting and Using Your Personal Data</h3>
        <div class="space-y-4">
          <div>
            <h4 class="font-semibold">Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain personally identifiable information
              that can be used to contact or identify You. Personally identifiable information may include, but is not
              limited to:
            </p>
            <ol>
              <li>- First name and last name</li>
              <li>- Email address</li>
              <li>- Usage data</li>
            </ol>
          </div>
          <div>
            <h4 class="font-semibold">Usage Data</h4>
            <div class="space-y-2">
              <p>Usage Data is collected automatically when using the Service.</p>
              <p>
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
                browser type, browser version, the pages of our Service that You visit, the time and date of Your visit,
                the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p>
                When You access the Service by or through a mobile device, We may collect certain information
                automatically, including, but not limited to, the type of mobile device You use, Your mobile device
                unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
                Internet browser You use, unique device identifiers and other diagnostic data.
              </p>
              <p>
                We may also collect information that Your browser sends whenever You visit our Service or when You
                access the Service by or through a mobile device.
              </p>
            </div>
          </div>
          <div>
            <h3 class="font-semibold">Information from Third-Party Social Media Services</h3>
            <div class="space-y-2">
              <p>
                The Company allows You to create an account and log in to use the Service through the Third-party Social
                Media Services "Google"
              </p>
              <p>
                If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We
                may collect Personal data that is already associated with Your Third-Party Social Media Service's
                account such as Your name, Your email address for help you Login faster in Our app. And We use your
                Google Drive account to store Your uploaded photo, so You will responsible with Your photos because We
                don't store in our storage
              </p>
            </div>
          </div>
          <div>
            <h3 class="font-semibold">Tracking Technologies and Cookies</h3>
            <div class="space-y-2">
              <p>
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
                information. Tracking technologies used are beacons, tags, and scripts to collect and track information
                and to improve and analyze Our Service. The technologies We use may include:
              </p>
              <ul>
                <li>
                  <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can
                  instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if
                  You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have
                  adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                </li>
              </ul>
              <p>
                Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your
                personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You
                close Your web browser. Learn more about cookies on the
                <a
                  href="https://www.privacypolicies.com/blog/privacy-policy-template/#Use_Of_Cookies_Log_Files_And_Tracking"
                  target="_blank"
                  >Privacy Policies website</a
                >
                article.
              </p>
              <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
              <ul class="space-y-4 pl-4">
                <li>
                  <p><strong>Necessary / Essential Cookies</strong></p>
                  <p>Type: Session Cookies</p>
                  <p>Administered by: Us</p>
                  <p>
                    Purpose: These Cookies are essential to provide You with services available through the Website and
                    to enable You to use some of its features. They help to authenticate users and prevent fraudulent
                    use of user accounts. Without these Cookies, the services that You have asked for cannot be
                    provided, and We only use these Cookies to provide You with those services.
                  </p>
                </li>
                <li>
                  <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                  <p>Type: Persistent Cookies</p>
                  <p>Administered by: Us</p>
                  <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                </li>
                <li>
                  <p><strong>Functionality Cookies</strong></p>
                  <p>Type: Persistent Cookies</p>
                  <p>Administered by: Us</p>
                  <p>
                    Purpose: These Cookies allow us to remember choices You make when You use the Website, such as
                    remembering your login details or language preference. The purpose of these Cookies is to provide
                    You with a more personal experience and to avoid You having to re-enter your preferences every time
                    You use the Website.
                  </p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div>
        <h3 class="font-semibold">4. Use of Your Personal Data</h3>
        <div class="space-y-4">
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul class="space-y-2">
            <li>
              <p>
                <strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.
              </p>
            </li>
            <li>
              <p>
                <strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The
                Personal Data You provide can give You access to different functionalities of the Service that are
                available to You as a registered user.
              </p>
            </li>
            <li>
              <p>
                <strong>For the performance of a contract:</strong> the development, compliance and undertaking of the
                purchase contract for the products, items or services You have purchased or of any other contract with
                Us through the Service.
              </p>
            </li>
            <li>
              <p>
                <strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent
                forms of electronic communication, such as a mobile application's push notifications regarding updates
                or informative communications related to the functionalities, products or contracted services, including
                the security updates, when necessary or reasonable for their implementation.
              </p>
            </li>
            <li>
              <p>
                <strong>To provide You</strong> with news, special offers and general information about other goods,
                services and events which we offer that are similar to those that you have already purchased or enquired
                about unless You have opted not to receive such information.
              </p>
            </li>
            <li>
              <p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
            </li>
            <li>
              <p>
                <strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger,
                divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our
                assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in
                which Personal Data held by Us about our Service users is among the assets transferred.
              </p>
            </li>
            <li>
              <p>
                <strong>For other purposes</strong>: We may use Your information for other purposes, such as data
                analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to
                evaluate and improve our Service, products, services, marketing and your experience.
              </p>
            </li>
          </ul>
        </div>
      </div>
      <div>
        <h3 class="font-semibold">5. Security of Your Personal Data</h3>
        <div class="space-y-4">
          <p>
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the
            Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable
            means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>
        </div>
      </div>
      <div>
        <h3 class="font-semibold">6. Links to Other Websites</h3>
        <div class="space-y-4">
          <p>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party
            link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy
            of every site You visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any
            third party sites or services.
          </p>
        </div>
      </div>
      <div>
        <h3 class="font-semibold">7. Changes to this Privacy Policy</h3>
        <div class="space-y-4">
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
            Privacy Policy on this page.
          </p>
          <p>
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming
            effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
            are effective when they are posted on this page.
          </p>
        </div>
      </div>
      <div>
        <h3 class="font-semibold">8. Contact Us</h3>
        <div class="space-y-4">
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>By email: support@pointhub.app</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts"></script>
